### ISSUE TITLE
Incredibly tight runtime dependency requirement

### ISSUE THREAD

**Issue by leoarnold** [rrrene/inch#44] opened 2017-11-02 23:02 UTC
I'd like to use this gem in the same `Gemfile` with `puppet-strings`, but due to Inch's incredibly thight requirement

```ruby
spec.add_dependency 'yard', '~> 0.8.7.5'
```

Bundler returns

```
Bundler could not find compatible versions for gem "yard":
  In Gemfile:
    inch (~> 0.7) was resolved to 0.7.1, which depends on
      yard (~> 0.8.7.5)

    puppet-strings (~> 1.1) was resolved to 1.1.1, which depends on
      yard (~> 0.9.5)
```

The only viable version of Inch to go with `puppet-strings` v1 would be **Inch 0.0.1**.

**Comment by rrrene** [comment] 2017-11-04 19:43
I am closing this as a duplicate of #42 (that issue's discussion shows the reasons for the requirement as well as my willingness to accept a PR alleviating the situation) :+1:

On a side note, since you seem to be new to this: It is not a good idea to start the title of your Issue with a loaded phrase like "incredibly tight requirement". You are filing a request to an open source project after all. That's like going into someone's shop and starting the conversation with "Hi, my name is Leo and you don't know how to do your job!"

**Closed by rrrene** 2017-11-04 19:43 UTC
