### ISSUE TITLE
RDoc support

### ISSUE THREAD

**Issue by gettalong** [rrrene/inch#28] opened 2015-03-19 20:33 UTC
Hi,

just wanted to test this tool but I found that it doesn't really support RDoc. It seems to always use Yard for getting the data, there is no way to use RDoc, at least I didn't find any CLI option. (Yard throws an error when used on my codebase, so that's not really helpful -- but that's is naturally not the problem of inch).

Please consider adding real RDoc support - thanks!

Cheers,
  Thomas

**Comment by rrrene** [comment] 2015-03-20 07:27
[It *seems*](https://github.com/lsegal/yard/issues/846) your problem was due to a bug in Ripper (which was a known issue that boggled me all year), which was fixed in Ruby 2.2.1 - can you confirm this?

**Comment by gettalong** [comment] 2015-03-20 08:59
Yes, the upgrade to Ruby 2.2.1 fixes the Yard error.

However, inch still uses YARD for getting the documentation and not RDoc. So people using Yard might getting the expected results but since Yard differs from RDoc the output is not completely what I would expect.

**Comment by rrrene** [comment] 2015-03-20 09:09
Could you point me to an example? Since Inch does actually just leverage YARD's use of Ripper at this point and *should* parse RDoc comments itself.

**Comment by gettalong** [comment] 2015-03-20 09:22
For example, I get false positives for the members of Struct classes.

**Comment by rrrene** [comment] 2015-03-20 09:53
Could you give an example of how you document members of Structs in RDoc? 

btw: Why are you so vague? You are the maintainer of `kramdown`, you should know how to file a *constructive* bug report (as opposed to just saying "this does not really support X, fix it"). Provide a link or a small code sample, describe the desired outcome and how the current implementation falls short.

**Comment by gettalong** [comment] 2015-03-20 10:42
I'm sorry but I don't have time to look at the inch code or how it uses Yard. What I noticed when I ran inch was a bug in Yard and I said that this is not related to inch (I filed a bug report and got pointed to the solution).

However, from the error message I saw that inch uses Yard and I tried to find an option to use RDoc instead of Yard (since the inch homepage mentions RDoc support) but I didn't find any. Therefore I asked if you consider supporting RDoc itself as well as Yard since I think using RDoc would deliver better results than using Yard when the developer itself uses RDoc.

As for "this does not really support X, fix it": I never said "fix it", I asked if RDoc could be supported. And I did dabble in RDoc's code a bit when I needed to but I never used Yard or inch and I currently don't have spare time to investigate all possible differences between Yard and RDoc and what this might mean for inch. So if Yard is an integral part of inch, there might be nothing that can be done about this which is okay, it is your decision.

As for documenting members of Structs: This depends entirely on the Struct class itself. Sometimes I use a codeblock with a call-seq like line to show the members when their meaning is apparent from their name, sometimes I use RDoc's labeled lists to describe them.

**Comment by rrrene** [comment] 2015-03-20 11:04
@gettalong Maybe we got off on the wrong foot here. I seriously want to try to support the thing you describe since Inch "has" RDoc support, but it is not perfect.

What I critized about the bug report was a mixture of wording and missing information to reproduce a bug that I am sure exists. Inch states in its README that it supports RDoc and even comes with [fixtures that are tested for RDoc support](https://github.com/rrrene/inch/blob/master/test/fixtures/ruby/simple/lib/foo.rb#L58), so "I found that it doesn't *really* support RDoc" maybe rubbed me the wrong way.

If you could come up with a sample doc string like

    # This is a test class.
    #
    # Members:
    # +a+:: a string
    # +b+:: +Proc+ object (may be nil)
    class Test < Struct.new(:a, :b)
    end

 that I could try to evaluate correctly and add to the testsuite, it would be much appreciated. :+1:

**Comment by gettalong** [comment] 2015-03-20 11:50
You are completely right, it is obviously not a good bug report, sorry.

And I should probably also clarify: RDoc means two things, the documentation format and the tool to parse the documentation format. When I use RDoc the tool for generating the documentation I get the info that no method is undocumented in the sense meant by RDoc. The result would probably be different when using YARD the tool. When reading the documentation I probably jumped to the conclusion that inch supports RDoc the tool whereas it supports RDoc the documentation format.

This is what I currently have for the Struct class in question:

~~~
# One entry of a cross-reference section or stream.
#
# An entry has the attributes +type+, +oid+, +gen+, +pos+ and +objstm+ and can be created like
# this:
#
#   Entry.new(type, oid, gen, pos, objstm)   -> entry
#
# The +type+ attribute can be:
#
# :free:: Denotes a free entry.
#
# :in_use:: A used entry that resides in the body of the PDF file. The +pos+ attribute defines
#           the position in the file at which the object can be found.
#
# :compressed:: A used entry that resides in an object stream. The +objstm+ attribute contains
#               the reference to the object stream in which the object can be found and the
#               +pos+ attribute contains the index into the object stream.
#
#               Objects in an object stream always have a generation number of 0!
#
# See: PDF1.7 s7.5.4, s7.5.8
Entry = Struct.new(:type, :oid, :gen, :pos, :objstm)
~~~

The values for `type` are documented and within them the meaning of `pos` and `objstm` values. As for `oid` and `gen` they are self-explanatory in this context.

**Comment by rrrene** [comment] 2015-03-20 14:49
Alright, I will try to include this in the next release.

Thanks for the example!

**Comment by gettalong** [comment] 2015-03-20 17:22
Thanks for you patience!

**Comment by rrrene** [comment] 2023-01-26 19:38
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.

**Closed by rrrene** 2023-01-26 19:38 UTC
